name: Build and push image workflow
on:
  push:
    branches: 
      - development
      - staging
      - master

env:
  APP_NAME: "action-env"

jobs:
  environment-check:
    runs-on: ubuntu-latest
    steps:
    - name: 'Get environment name'
      id: "get-environment"
      run: |
        env="${{ github.ref_name }}"
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          env="production"
        fi
        echo "GETENV=${env}" >> $GITHUB_OUTPUT

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: ["environment-check"]
    environment: 
      name: ${{ steps.get-environment.outputs.GETENV }}
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ github.ref_name }}