name: Build and push image workflow
on:
  push:
    branches: 
      - development
      - staging
      - master

env:
  APP_NAME: "action-env"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name }}
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ github.ref_name }}