name: Build and push image workflow
on:
  push:
    branches: 
      - development
      - staging
      - master

env:
  APP_NAME: "action-env"

jobs:
  get-environment:
    runs-on: ubuntu-latest
    outputs:
      GETENV: ${{ steps.get-env.outputs.GETENV }}
    steps:
    - name: 'Get environment name'
      id: get-env
      run: |
        env="${{ github.ref_name }}"
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          env="production"
        fi
        echo "GETENV=${env}" >> $GITHUB_OUTPUT

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: ["get-environment"]
    env:
      GETENV: ${{ needs.get-environment.outputs.GETENV }}
    environment: 
      name: ${{ env.GETENV }}
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Get environment name'
      run: |
        echo ${{ env.GETENV }}
      
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/${{ env.APP_NAME }}:${{ env.GETENV }}